url: ''
baseurl: 'https://collapps.co'
title: 'Collapps'

plugins:
  - jekyll-postcss

postcss:
  cache: false

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
